[server]
maxUploadSize = 500
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#92400E"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#F1F5F9"
textColor = "#0F172A"
